services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - mongodb

  frontend:
    build: ./frontend
    ports:
      - "3000:80"

  mongodb:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db   # ✅ persistent volume

volumes:
  mongo_data:
